//! The supported public surface, written down and compared against the source.
//!
//! `#[doc(hidden)]` marks `internals` and `unwind` as unsupported, but it is a
//! convention rather than an enforcement: it hides a module from the rendered
//! documentation and stops nobody from depending on it. The risk that actually
//! needs a mechanism is the other one — the *supported* surface growing by
//! accident, one convenient `pub` at a time, until a thing nobody decided to
//! promise is a thing that cannot be changed before 1.0.
//!
//! So the surface is a committed file. Adding to it is one line in a diff and a
//! reviewer's decision; adding to it without noticing is a failing test.
//!
//! # What this covers, and what it does not
//!
//! Covered: every public module reachable from the crate root without passing
//! through a `#[doc(hidden)]` one, and within those modules every public item,
//! struct field, enum variant, inherent `pub fn` and `pub const`, trait
//! implementation (written or derived), `#[non_exhaustive]` marker, re-export
//! *with the path it re-exports*, and `#[macro_export]` macro.
//!
//! Not covered: anything a scan of the source cannot see. Trait implementations
//! generated by a macro, blanket implementations, and auto-traits (`Send`,
//! `Sync`, `Unpin`) are absent, so this does not catch a private field change
//! that makes a public type `!Send`. That is a real gap and the reason this is a
//! tripwire rather than a proof.
//!
//! # Updating it
//!
//! `cargo test --test public_surface -- --ignored --exact rewrite_the_snapshot`
//! rewrites the file, and the change then shows up in review as itself.
//!
//! It is deliberately not an environment variable. The variable that turns a
//! gate into a recorder is the one that gets read wrong — `HEAPSCOPE_UPDATE_BASELINE`
//! spent a chunk being read as *on* when set to `FALSE` — and a rule with no
//! spellings has no spelling to get wrong.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

// Every test here reads the repository from disk, which Miri turns into a hard
// machine abort rather than an `io::Error`. Same treatment as
// `tests/no_dependencies.rs`, and for the same reason.

/// Where the committed surface lives.
const SNAPSHOT: &str = "tests/data/public_surface.txt";

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

// ---------------------------------------------------------------------------
// The scanner
// ---------------------------------------------------------------------------

/// An item's kind, as it appears at the start of a snapshot line.
///
/// Spelled out rather than reusing the Rust keyword so that `use` and `impl`
/// lines, which carry more than a name, are visibly a different shape.
const ITEM_KEYWORDS: &[&str] = &[
    "mod", "struct", "enum", "trait", "type", "const", "static", "fn", "use", "unsafe",
];

/// Collects the surface of one crate, starting at its root module.
///
/// Panics on anything it cannot parse. That is the whole discipline: a scanner
/// that skips what it does not recognise reports a smaller surface than the
/// crate has, and the snapshot then agrees with it — a test passing for a
/// reason nobody wrote down, which is the failure mode this repository keeps
/// meeting.
fn scan_crate(root: &Path) -> BTreeSet<String> {
    let mut surface = BTreeSet::new();
    scan_module(&root.join("src/lib.rs"), "heapscope", None, &mut surface);
    surface
}

/// Reads one module.
///
/// `only` is `None` for a module that is itself public, and `Some(names)` when
/// a re-export has reached into a module that is not: `Profiler` lives in a
/// private `mod profiler` and `Mode` in a `#[doc(hidden)]` one, so their fields
/// and methods are supported surface reachable only through the name that
/// re-exports them. A filtered read records those under the path they are
/// exported at, and does not follow anything further out of the module.
fn scan_module(
    file: &Path,
    module_path: &str,
    only: Option<&BTreeSet<String>>,
    surface: &mut BTreeSet<String>,
) {
    let text = std::fs::read_to_string(file)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", file.display()));
    let lines: Vec<&str> = text.lines().collect();

    let dir = file.parent().expect("a source file has a parent directory");
    // `src/lib.rs` and `src/symbol/mod.rs` own their directory; `src/stats.rs`
    // would own `src/stats/`.
    let child_dir = if matches!(
        file.file_name().and_then(|n| n.to_str()),
        Some("lib.rs") | Some("mod.rs")
    ) {
        dir.to_path_buf()
    } else {
        dir.join(file.file_stem().expect("a source file has a stem"))
    };

    let mut i = 0;
    while i < lines.len() {
        // Anything indented belongs to an item already accounted for, and
        // `#![..]` is about the crate rather than about what follows it.
        let line = lines[i];
        if line.trim().is_empty() || line.starts_with(' ') || line.starts_with("//") {
            i += 1;
            continue;
        }
        if line.starts_with("#!") {
            join_until(&lines, &mut i, |l| l.trim_end().ends_with(']'));
            continue;
        }

        // Gather the attributes and doc comments sitting above the next item.
        let mut hidden = false;
        let mut exported_macro = false;
        let mut non_exhaustive = false;
        let mut derives: Vec<String> = Vec::new();
        while i < lines.len() {
            let line = lines[i];
            if line.starts_with("//") {
                i += 1;
                continue;
            }
            if !line.starts_with("#[") {
                break;
            }
            let attr = join_until(&lines, &mut i, |l| l.trim_end().ends_with(']'));
            let attr = attr.trim();
            // `#[cfg(test)]` items are not compiled into the shipped library at
            // all, so they are not surface whatever they are marked.
            if attr == "#[cfg(test)]" {
                hidden = true;
            }
            if attr.contains("doc(hidden)") {
                hidden = true;
            }
            if attr == "#[macro_export]" {
                exported_macro = true;
            }
            if attr == "#[non_exhaustive]" {
                non_exhaustive = true;
            }
            if let Some(list) = attr
                .strip_prefix("#[derive(")
                .and_then(|s| s.strip_suffix(")]"))
            {
                // A derive list rustfmt has broken over several lines arrives
                // here joined, and a trailing comma then yields an empty name.
                derives.extend(
                    list.split(',')
                        .map(str::trim)
                        .filter(|t| !t.is_empty())
                        .map(str::to_string),
                );
            }
        }
        if i >= lines.len() {
            break;
        }
        // What the attributes were attached to may turn out to be nothing at
        // all, in which case they belonged to nothing and are dropped.
        let line = lines[i];
        if line.trim().is_empty() || line.starts_with(' ') {
            i += 1;
            continue;
        }

        if line.starts_with("impl ") || line.starts_with("impl<") {
            let at = i;
            let header = join_until(&lines, &mut i, |l| l.contains('{'));
            let (subject, implemented) = parse_impl_header(&header, file, at);
            let wanted = !hidden && only.is_none_or(|names| names.contains(&subject));
            if wanted {
                if let Some(tr) = implemented {
                    surface.insert(format!("impl {module_path}::{subject}: {tr}"));
                }
            }
            // A trailing `{}` is a body already closed.
            if !header.trim_end().ends_with("{}") {
                if wanted {
                    scan_impl_body(&lines, &mut i, module_path, &subject, surface);
                } else {
                    // Already one line past the header, so the body is what is
                    // left to walk off.
                    while i < lines.len() && lines[i] != "}" {
                        i += 1;
                    }
                    i += 1;
                }
            }
            continue;
        }

        if line.starts_with("macro_rules!") {
            let name = ident_after(line, "macro_rules!", file, i);
            if exported_macro {
                // `#[macro_export]` puts a macro at the crate root whatever
                // module it is written in.
                surface.insert(format!("macro heapscope::{name}"));
            }
            skip_block(&lines, &mut i);
            continue;
        }

        if !line.starts_with("pub ") {
            // A private item. Still has to be skipped as a block so its body is
            // never mistaken for surface.
            skip_item(&lines, &mut i);
            continue;
        }

        // `pub unsafe fn` is an `fn` whose safety is part of its signature
        // rather than a separate kind of item.
        let after_pub = &line["pub ".len()..];
        let after_pub = after_pub.strip_prefix("unsafe ").unwrap_or(after_pub);
        let keyword = after_pub
            .split_whitespace()
            .next()
            .unwrap_or_else(|| panic!("{}:{}: `pub` with nothing after it", file.display(), i + 1));
        assert!(
            ITEM_KEYWORDS.contains(&keyword),
            "{}:{}: unrecognised public item `{}`. This scanner must be taught \
             the form before the surface can be trusted.",
            file.display(),
            i + 1,
            line.trim()
        );

        match keyword {
            "mod" => {
                let name = ident_after(after_pub, "mod", file, i);
                if !hidden && only.is_none() {
                    surface.insert(format!("mod {module_path}::{name}"));
                    let child = module_file(&child_dir, &name).unwrap_or_else(|| {
                        panic!("{}:{}: no file for `pub mod {name}`", file.display(), i + 1)
                    });
                    scan_module(&child, &format!("{module_path}::{name}"), None, surface);
                }
                i += 1;
            }
            "use" => {
                let at = i;
                let stmt = join_until(&lines, &mut i, |l| l.trim_end().ends_with(';'));
                if !hidden && only.is_none() {
                    for (exported, source) in parse_use(&stmt, file, at) {
                        surface.insert(format!("use {module_path}::{exported} = {source}"));
                        follow_reexport(&child_dir, &source, module_path, file, at, surface);
                    }
                }
            }
            _ => {
                let name = ident_after(after_pub, keyword, file, i);
                let wanted = !hidden && only.is_none_or(|names| names.contains(&name));
                let qualified = format!("{module_path}::{name}");
                if wanted {
                    surface.insert(format!("{keyword} {qualified}"));
                    if non_exhaustive {
                        surface.insert(format!("attr {qualified} #[non_exhaustive]"));
                    }
                    for tr in &derives {
                        surface.insert(format!("impl {qualified}: {tr} (derived)"));
                    }
                }
                let members = matches!(keyword, "struct" | "enum");
                if members && line.trim_end().ends_with('{') {
                    scan_members(&lines, &mut i, &qualified, keyword, !wanted, surface);
                } else {
                    skip_item(&lines, &mut i);
                }
            }
        }
    }
}

/// Returns the identifier following `keyword` in `text`.
fn ident_after(text: &str, keyword: &str, file: &Path, line: usize) -> String {
    let rest = text
        .split_once(keyword)
        .unwrap_or_else(|| {
            panic!(
                "{}:{}: expected `{keyword}` in `{}`",
                file.display(),
                line + 1,
                text.trim()
            )
        })
        .1;
    let name: String = rest
        .trim_start()
        .chars()
        .take_while(|c| c.is_alphanumeric() || *c == '_')
        .collect();
    assert!(
        !name.is_empty(),
        "{}:{}: no name after `{keyword}` in `{}`",
        file.display(),
        line + 1,
        text.trim()
    );
    name
}

/// Joins lines from `*i` until `done` holds, leaving `*i` one past the last.
fn join_until(lines: &[&str], i: &mut usize, done: impl Fn(&str) -> bool) -> String {
    let mut joined = String::new();
    while *i < lines.len() {
        let line = lines[*i];
        if !joined.is_empty() {
            joined.push(' ');
        }
        joined.push_str(line.trim());
        *i += 1;
        if done(line) {
            break;
        }
    }
    joined
}

/// Advances past an item, whether it is a one-liner or a braced block.
///
/// Only a line that actually opens a brace is followed to a closing one. A
/// scanner that guessed here would swallow the rest of the file and report a
/// surface of nothing, which every snapshot would then agree with.
fn skip_item(lines: &[&str], i: &mut usize) {
    let line = lines[*i].trim_end();
    if line.ends_with('{') {
        skip_block(lines, i);
    } else {
        *i += 1;
    }
}

/// Advances past a braced block whose closing `}` is at column zero.
fn skip_block(lines: &[&str], i: &mut usize) {
    *i += 1;
    while *i < lines.len() {
        if lines[*i] == "}" {
            *i += 1;
            return;
        }
        *i += 1;
    }
}

/// Reads the public members of a `struct` or `enum` body.
fn scan_members(
    lines: &[&str],
    i: &mut usize,
    qualified: &str,
    keyword: &str,
    hidden: bool,
    surface: &mut BTreeSet<String>,
) {
    *i += 1;
    while *i < lines.len() && lines[*i] != "}" {
        let line = lines[*i];
        *i += 1;
        // Members sit at exactly one level of indentation; anything deeper
        // belongs to a member and is not itself surface.
        if line.len() - line.trim_start().len() != 4 {
            continue;
        }
        let trimmed = line.trim();
        if trimmed.starts_with("//") || trimmed.starts_with('#') || trimmed.is_empty() {
            continue;
        }
        if hidden {
            continue;
        }
        match keyword {
            "struct" => {
                if let Some(field) = trimmed.strip_prefix("pub ") {
                    let name = field
                        .split(':')
                        .next()
                        .expect("split always yields one part")
                        .trim();
                    surface.insert(format!("field {qualified}::{name}"));
                }
            }
            "enum" => {
                let name: String = trimmed
                    .chars()
                    .take_while(|c| c.is_alphanumeric() || *c == '_')
                    .collect();
                if !name.is_empty() {
                    surface.insert(format!("variant {qualified}::{name}"));
                }
            }
            _ => unreachable!("only structs and enums have members here"),
        }
    }
    *i += 1;
}

/// Reads the inherent `pub fn` and `pub const` of an `impl` body.
fn scan_impl_body(
    lines: &[&str],
    i: &mut usize,
    module_path: &str,
    subject: &str,
    surface: &mut BTreeSet<String>,
) {
    while *i < lines.len() && lines[*i] != "}" {
        let line = lines[*i];
        *i += 1;
        if line.len() - line.trim_start().len() != 4 {
            continue;
        }
        let Some(rest) = line.trim().strip_prefix("pub ") else {
            continue;
        };
        // A trait implementation's methods are not `pub`, so anything reaching
        // here is inherent.
        let rest = rest.strip_prefix("const ").unwrap_or(rest);
        let rest = rest.strip_prefix("unsafe ").unwrap_or(rest);
        let rest = rest.strip_prefix("fn ").unwrap_or(rest);
        let name: String = rest
            .chars()
            .take_while(|c| c.is_alphanumeric() || *c == '_')
            .collect();
        if !name.is_empty() {
            surface.insert(format!("fn {module_path}::{subject}::{name}"));
        }
    }
    *i += 1;
}

/// Splits `impl [<generics>] [Trait for] Type [where ...] {` into the type it
/// is about and the trait it implements, if any.
fn parse_impl_header(header: &str, file: &Path, line: usize) -> (String, Option<String>) {
    let body = header
        .trim()
        .strip_prefix("impl")
        .unwrap_or_else(|| panic!("{}:{}: not an impl header", file.display(), line));
    // Drop the generic parameter list, which may itself contain `for` in a
    // higher-ranked bound.
    let body = strip_leading_generics(body);
    let body = body.split(" where ").next().expect("split yields one part");
    let body = body
        .split('{')
        .next()
        .expect("split yields one part")
        .trim();
    let (trait_part, type_part) = match body.split_once(" for ") {
        Some((t, ty)) => (Some(t.trim().to_string()), ty.trim()),
        None => (None, body),
    };
    let subject = strip_generic_args(type_part);
    assert!(
        !subject.is_empty(),
        "{}:{}: could not find the type an impl is about",
        file.display(),
        line
    );
    (subject, trait_part)
}

fn strip_leading_generics(text: &str) -> &str {
    let text = text.trim_start();
    if !text.starts_with('<') {
        return text;
    }
    let mut depth = 0usize;
    for (idx, ch) in text.char_indices() {
        match ch {
            '<' => depth += 1,
            '>' => {
                depth -= 1;
                if depth == 0 {
                    return text[idx + 1..].trim_start();
                }
            }
            _ => {}
        }
    }
    text
}

/// `Symbolized<'a>` is the same item as `Symbolized`; the lifetime is not part
/// of what the surface promises.
fn strip_generic_args(text: &str) -> String {
    text.split('<')
        .next()
        .expect("split yields one part")
        .trim()
        .to_string()
}

/// Resolves `name` as a child module of `dir`, either `name.rs` or `name/mod.rs`.
fn module_file(dir: &Path, name: &str) -> Option<PathBuf> {
    [
        dir.join(format!("{name}.rs")),
        dir.join(name).join("mod.rs"),
    ]
    .into_iter()
    .find(|p| p.exists())
}

/// Reads a re-exported item's own surface out of the module that defines it.
///
/// `Profiler` is `pub` inside a private `mod profiler` and `Mode` inside a
/// `#[doc(hidden)]` one. Both are supported surface, and their fields, variants
/// and methods are supported with them — so the definition has to be read even
/// though the module holding it is not itself public. Anything the re-export
/// names that turns out to be a function or a constant simply has no members to
/// find, and contributes nothing here.
fn follow_reexport(
    child_dir: &Path,
    source: &str,
    module_path: &str,
    file: &Path,
    line: usize,
    surface: &mut BTreeSet<String>,
) {
    // `crate::` restarts from the crate root; everything else is relative to
    // the module doing the re-exporting.
    let (base, path) = match source.strip_prefix("crate::") {
        Some(rest) => (crate_src(child_dir), rest),
        None => (child_dir.to_path_buf(), source),
    };
    let mut segments: Vec<&str> = path.split("::").collect();
    let Some(item) = segments.pop() else {
        panic!("{}:{}: empty re-export path", file.display(), line + 1);
    };
    if segments.is_empty() {
        // A re-export of something in this very module; already covered.
        return;
    }

    let mut dir = base;
    let mut target = None;
    for (depth, segment) in segments.iter().enumerate() {
        let found = module_file(&dir, segment).unwrap_or_else(|| {
            panic!(
                "{}:{}: `pub use {source};` names module `{segment}`, which is not \
                 a file under {}. The scanner must be able to reach a re-export's \
                 definition or it will under-report the surface.",
                file.display(),
                line + 1,
                dir.display()
            )
        });
        dir = if found.file_name().and_then(|n| n.to_str()) == Some("mod.rs") {
            found.parent().expect("mod.rs has a parent").to_path_buf()
        } else {
            dir.join(segment)
        };
        if depth + 1 == segments.len() {
            target = Some(found);
        }
    }

    let target = target.expect("segments is non-empty");
    let wanted: BTreeSet<String> = [item.to_string()].into_iter().collect();
    scan_module(&target, module_path, Some(&wanted), surface);
}

/// Walks up from a module's directory to the `src` the crate root lives in.
fn crate_src(child_dir: &Path) -> PathBuf {
    let mut dir = child_dir;
    loop {
        if dir.join("lib.rs").exists() {
            return dir.to_path_buf();
        }
        dir = dir
            .parent()
            .unwrap_or_else(|| panic!("no lib.rs above {}", child_dir.display()));
    }
}

/// Reads `pub use path::{a, b as c};` into `(exported name, source path)` pairs.
///
/// The source path is kept because a re-export that starts pointing somewhere
/// else keeps its name while changing its meaning, which is precisely the
/// change a snapshot on names alone would miss.
fn parse_use(stmt: &str, file: &Path, line: usize) -> Vec<(String, String)> {
    let body = stmt
        .trim()
        .strip_prefix("pub use ")
        .and_then(|s| s.strip_suffix(';'))
        .unwrap_or_else(|| panic!("{}:{}: cannot read `{stmt}`", file.display(), line))
        .trim();

    let (prefix, names) = match body.split_once('{') {
        Some((prefix, rest)) => {
            let inner = rest
                .strip_suffix('}')
                .unwrap_or_else(|| panic!("{}:{}: unclosed use group", file.display(), line));
            (prefix.trim().to_string(), inner.split(',').collect())
        }
        None => (String::new(), vec![body]),
    };

    names
        .into_iter()
        .map(str::trim)
        .filter(|n| !n.is_empty())
        .map(|entry| {
            let (path, alias) = match entry.split_once(" as ") {
                Some((p, a)) => (p.trim(), Some(a.trim())),
                None => (entry, None),
            };
            let full = format!("{prefix}{path}");
            let exported = alias.map(str::to_string).unwrap_or_else(|| {
                full.rsplit("::")
                    .next()
                    .expect("rsplit yields one part")
                    .to_string()
            });
            (exported, full)
        })
        .collect()
}

fn render(surface: &BTreeSet<String>) -> String {
    let mut out = String::new();
    out.push_str("# The supported public surface of `heapscope`.\n");
    out.push_str("# Generated by `tests/public_surface.rs`; see that file to update it.\n");
    for line in surface {
        let _ = writeln!(out, "{line}");
    }
    out
}

// ---------------------------------------------------------------------------
// The tests
// ---------------------------------------------------------------------------

#[test]
#[cfg_attr(
    miri,
    ignore = "reads the repository from disk; Miri has no filesystem"
)]
fn the_public_surface_is_what_was_agreed() {
    let root = repo_root();
    let found = scan_crate(&root);

    // A scanner that returned nothing would agree with an empty snapshot. These
    // are the anchors: if they are missing the scan is broken, whatever the
    // snapshot says.
    for anchor in [
        "use heapscope::Profiler = profiler::Profiler",
        "mod heapscope::stats",
        "macro heapscope::assert_max_bytes",
        "struct heapscope::stats::HeapStats",
    ] {
        assert!(
            found.contains(anchor),
            "the scan did not find `{anchor}`, so it is not reading the crate"
        );
    }
    // A hidden module may be *named* — the source path of a re-export is part
    // of what is recorded — but nothing may be reachable *at* a path inside one.
    let leaked: Vec<&String> = found
        .iter()
        .filter(|item| item.contains("heapscope::internals") || item.contains("heapscope::unwind"))
        .filter(|item| !item.starts_with("use "))
        .collect();
    assert!(
        leaked.is_empty(),
        "a `#[doc(hidden)]` module was walked into; it is not supported surface: {leaked:?}"
    );

    let path = root.join(SNAPSHOT);
    let committed = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "cannot read {SNAPSHOT}: {e}\n\
             If it does not exist yet, write it with:\n  \
             cargo test --test public_surface -- --ignored --exact rewrite_the_snapshot"
        )
    });
    let expected: BTreeSet<String> = committed
        .lines()
        .filter(|l| !l.trim().is_empty() && !l.trim_start().starts_with('#'))
        .map(str::to_string)
        .collect();

    let added: Vec<&String> = found.difference(&expected).collect();
    let removed: Vec<&String> = expected.difference(&found).collect();

    if added.is_empty() && removed.is_empty() {
        return;
    }

    let mut message = String::from("the public surface is not what `");
    let _ = write!(message, "{SNAPSHOT}` says it is.\n\n");
    if !added.is_empty() {
        message.push_str("added (not previously promised):\n");
        for item in &added {
            let _ = writeln!(message, "  + {item}");
        }
    }
    if !removed.is_empty() {
        message.push_str("removed (previously promised):\n");
        for item in &removed {
            let _ = writeln!(message, "  - {item}");
        }
    }
    message.push_str(
        "\nIf every line above is a change somebody decided to make, record it with:\n  \
         cargo test --test public_surface -- --ignored --exact rewrite_the_snapshot\n",
    );
    panic!("{message}");
}

/// Rewrites the committed surface. Ignored by default: it is a tool, not a
/// check, and a check that repairs itself checks nothing.
#[test]
#[ignore = "rewrites tests/data/public_surface.txt; run it deliberately"]
#[cfg_attr(miri, ignore = "writes to the repository; Miri has no filesystem")]
fn rewrite_the_snapshot() {
    let root = repo_root();
    let surface = scan_crate(&root);
    let path = root.join(SNAPSHOT);
    std::fs::write(&path, render(&surface))
        .unwrap_or_else(|e| panic!("cannot write {}: {e}", path.display()));
    println!("wrote {} items to {SNAPSHOT}", surface.len());
}
